version: '3.5'

services:
  talker:
    build: .
    container_name: talker
    environment:
      - "ROS_HOSTNAME=talker"
    command: roslaunch talker talker.launch
    networks:
      - rosnetwork

networks:
  rosnetwork:
    name: rosnetwork
